Fix param not passed

diff --git a/public/get b/public/get
--- a/public/get
+++ b/public/get
@@ -90,4 +90,4 @@ git remote get-url origin|grep -q $remote_repo || { echo "Dir \"$path\" is not e
 x git pull origin main && git submodule update --init --recursive
 echo "$me: Downloaded."
 echo "$me: Running \"./setup install\"."
-x ./setup install || { echo "$me: Error occured when running \"./setup install\"."; exit 1 ; }
+x ./setup install "$@" || { echo "$me: Error occured when running \"./setup install\"."; exit 1 ; }
