Update setup script

diff --git a/public/setup b/public/setup
--- a/public/setup
+++ b/public/setup
@@ -42,5 +42,5 @@ fi
 git remote get-url origin|grep -q $remote_repo || { echo "Dir \"$path\" is not empty, nor a git repo of $remote_repo. Aborting..."; exit 1 ; }
 x git pull origin main && git submodule update --init --recursive
 echo "$me: Downloaded."
-echo "$me: Running \"install.sh\"."
-x ./install.sh || { echo "$me: Error occured when running \"install.sh\"."; exit 1 ; }
+echo "$me: Running \"./setup install\"."
+x ./setup install || { echo "$me: Error occured when running \"./setup install\"."; exit 1 ; }
